configuration_as_code:
  unclassified:
    simple-theme-plugin:
      elements:
      - cssUrl:
          url: "/userContent/tci.css"
      - faviconUrl:
          url: "/userContent/tci-small-logo.png"

