environment:
  TCI_DEBUG_MODE: 'false'
  TCI_PIPELINES_BRANCH: 'master'
  TCI_DEFAULT_JDK_TOOL_NAME: 'jdk'
  TCI_DEFAULT_MAVEN_TOOL_NAME: 'maven'
  TCI_DEFAULT_MAVEN_SETTINGS_FILE_CONFIG_NAME: 'maven-settings'

