    labels:
      traefik.enable: "true"
      traefik.port: "${JENKINS_HTTP_PORT_FOR_SLAVES}"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host:tci.tikal.io"
    depends_on:
      - traefik
